language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - hexo-source # build hexo-source branch only
  except:
    - master
script:
  - hexo generate # generate static files
deploy:
  edge: true
  provider: pages:git
  cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  verbose: true
  target_branch: master # generate static files to master