language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install hexo-cli -g
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "krems04"
  - git config user.email "krems04@gmail.com"
  - git add -A
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - hexo-source
env:
 global:
   - GH_REF: github.com/krems04/krems04.github.io.git
